language: php

php:
  - 7.4

# environment variable used in test suite
env: TEST_ENVIRONMENT=travis

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - bin/.phpunit
    - $HOME/.symfony

# install dependencies
install:
  - travis_retry curl -sS https://get.symfony.com/cli/installer | bash && export PATH="$HOME/.symfony/bin:$PATH"
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --no-interaction

# run tests
script:
  - composer cs-check
  - ./bin/phpunit
