version: '3'

services:
  php-fpm:
    build: ./docker/php-fpm
    container_name: news_portal_php_fpm
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - mysql

  nginx:
    image: nginx:1.19
    container_name: news_portal_nginx
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.0
    container_name: news_portal_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./var/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: news_portal
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
